### ISSUE TITLE
Have to remove ?invert_in_darkmode to render images

### ISSUE THREAD

**Issue by kdavis-mozilla** [leegao/readme2tex#16]
First, thanks for writing this!

Second, after I generate via
```
python -m readme2tex --output README.md --readme .README.md --branch master --svgdir 'docs/gfx' --nocdn --rerender --usepackage 'tikz' --usepackage 'algorithm' --usepackage 'algpseudocode' --usepackage 'fancybox'
```

I get a `README.md` with svg image links all ending in `?invert_in_darkmode`. If I push these to github, the images are broken. However, if I remove `?invert_in_darkmode` from the generated document everything works fine.

Another point that might be relevant, this is for a private repo.

**Comment by leegao** [comment]
Ahh, that's definitely a problem, I'll add a flag to disable it. For the time being, you can try cloning this locally, modifying https://github.com/leegao/readme2tex/blob/master/readme2tex/render.py#L325 to be always False, and run

python setup.py develop

which will symlink the readme2tex directory to your local repo

**Comment by kdavis-mozilla** [comment]
@leegao Thanks! This quick fix works perfectly.
